---
version: "2.0"

services:
  app:
    image: dimokus88/ubuntu:1.1
    env:
     - "my_root_password=<YOUR-PASSWORD>"
#     - "link_key=<LINK-TO-YOUR-VALIDATOR-KEY>" 
     
    command:
      - "bash"
      - "-c"
    args:
      - 'curl -s https://raw.githubusercontent.com/Dimokus88/near/main/main.sh | bash '
    expose:
      - port: 22
        as: 22
        to:
          - global: true
      - port: 24567
        as: 24567
        to:
          - global: true
      - port: 3030
        as: 3030
        to:
          - global: true
profiles:
  compute:
    app:
      resources:
        cpu:
          units: 4.0
        memory:
          size: 8Gi
        storage:
          size: 100Gi
        
        
  placement:
    akash: 
      attributes:
        host: akash
      signedBy:
        anyOf:
            
      pricing:
        app:
          denom: uakt
          amount: 10000
deployment:
  app:
    akash:
      profile: app
      count: 1 